# Identificación del proyecto
sonar.projectKey=Feelin-Artist-Frontend
sonar.projectName=Feelin Artist Frontend
sonar.projectVersion=1.0

# SonarQube Server
sonar.host.url=http://localhost:9000
sonar.token=sqp_89f5e3a6929fa830ffda9f17444d3c40a25a0c1c

# Código fuente
sonar.sources=src,middleware.ts

# Exclusiones
sonar.exclusions=node_modules/**,.next/**,public/**,coverage/**

# Archivos TypeScript
sonar.typescript.tsconfigPath=tsconfig.json

# Encoding
sonar.sourceEncoding=UTF-8

# Coverage Jest/Vitest
sonar.javascript.lcov.reportPaths=coverage/lcov.info